environment: production
http_port: 8888
grpc_port: 8889
auth_secret: ######

database_uri: postgres://postgres:1234@localhost:5432/goshop?sslmode=disable

redis_uri: localhost:6379
redis_password:
redis_db: 0
